version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - rm -rf env/
      - python3 -m venv env
      - source env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      # we can run some tests here?
      # - flask run -h 0.0.0.0
      pytest flask_test/
  post_build:
    commands:
      - echo Build completed on `date`